### ISSUE TITLE
[bug] search is broken

### ISSUE THREAD

**Issue by SimonGolms** [opendevstack/ods-documentation#52]
1. Go to: https://www.opendevstack.org/ods-documentation
2. Search for e.g. `snyk`
3. Click on first search result `Stage Scan for Snyk`
4. Getting forwarded to: https://www.opendevstack.org/opendevstack/1.x/jenkins-shared-library/index.html#_stage_scan_for_snyk --> 404 Error Page

**Comment by michaelsauter** [comment]
I've investigated this and realised that the base path (`/ods-documentation`) is missing. The URL should be https://www.opendevstack.org/ods-documentation/opendevstack/1.x/jenkins-shared-library/index.html#_stage_scan_for_snyk.

Unfortunately I have not figured out how to fix it.

@rattermeyer Slightly related, would it be possible to get e.g. `docs.opendevstack.org` pointing to the documentation so that we do not have a base path?

**Comment by michaelsauter** [comment]
Not blocking v3, so taking it off from the release ...

**Comment by tbugfinder** [comment]
Hi @michaelsauter 
I don't understand why such issues are not timely tackled. This is the interface to users.

**Comment by tbugfinder** [comment]
As per my understanding supplemental_ui might be outdated.
https://github.com/Mogztter/antora-lunr/issues/67

**Comment by SimonGolms** [comment]
I don't know if the merge is already on prod but currently the search is not working at all anymore...

**Comment by michaelsauter** [comment]
@SimonGolms the merge is on prod but doesn't work (yet).

**Comment by tbugfinder** [comment]
Added another PR https://github.com/opendevstack/ods-documentation/pull/57 which fixed it.

**Comment by michaelsauter** [comment]
@tbugfinder Awesome, thanks!!

Now that it works, I added another issue regarding versioning in #58.
